// import Head from 'next/head'
// import { Inter } from 'next/font/google'
// import styles from '@/styles/Home.module.css'
// import Link from 'next/link'
// import { useRouter } from 'next/router'

// const inter = Inter({ subsets: ['latin'] })

// export default function Home() {
//     const router = useRouter()

//     const handleClick = () => {
//         console.log('Placing your order')
//         router.push('/product')
//     }

//     return (<>
//         <Head>
//             <title>Create Next App</title>
//             <meta name="description" content="Generated by create next app" />
//             <meta name="viewport" content="width=device-width, initial-scale=1" />
//             <link rel="icon" href="/favicon.ico" />
//         </Head>

//         <main>
//             <div>
//                 <Navbar/>
//                 <BackgroundWaves/>
//             </div>
//         </main>
//     </>)
// }

// -------------------------------------------------------------------

// import Head from 'next/head'
// import { Inter } from 'next/font/google'
// import styles from '@/styles/Home.module.css'
// import Link from 'next/link'
// import { useRouter } from 'next/router'
// import { useEffect, useState } from 'react';
// import { MainDesktop } from '@/components/Desktop/Main/MainDesktop';
// import { MainMobile } from '@/components/Mobile/Main/MainMobile';
// import {checkDevice} from '@/utils';

// const inter = Inter({ subsets: ['latin'] })

// export default function Home() {
//     var [style, setStyle] = useState("mobile-portrait")
    
//     function setDevice(){
//         setStyle(checkDevice())
//     }

//     useEffect(() => {
//         setDevice();
//         window.addEventListener('resize', setDevice);
//         return () => {
//             window.removeEventListener('resize', setDevice);
//         }
//     }, [])
    
//     return (<>
//          <main>
//              <div>
//                 {style === "desktop" ? <MainDesktop/> : style==="mobile-portrait" ? 
//                 <MainMobile />:<MainMobile/>}
//              </div>
//          </main>
//     </>);
// }


// -------------------------------------------------------------------
import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Link from 'next/link'
import { useRouter } from 'next/router'
import { useEffect, useState } from 'react';
import { MainDesktop } from '@/components/Desktop/Main/MainDesktop';
import { MainMobile } from '@/components/Mobile/Main/MainMobile';
// import {checkDevice} from '@/utils';
import {isMobile} from 'react-device-detect';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
    // var [style, setStyle] = useState("mobile-portrait")
    
    // function setDevice(){
    //     setStyle(checkDevice())
    // }

    // useEffect(() => {
    //     setDevice();
    //     window.addEventListener('resize', setDevice);
    //     return () => {
    //         window.removeEventListener('resize', setDevice);
    //     }
    // }, [])
    
    return (<>
         <main>
             <div>
                {isMobile? <MainMobile/> : <MainDesktop />}
             </div>
         </main>
    </>);
}

